# Usar la imagen oficial de Nginx como base
FROM nginx:alpine

# Copiar tu archivo de configuración personalizado al directorio de Nginx.
# Esto reemplazará la configuración por defecto con la tuya.
COPY nginx.conf /etc/nginx/conf.d/default.conf