server {
    listen 80;

    resolver 127.0.0.11 valid=5s;

    # Rutas para Startups
    location /v1/api/startups/create {
        proxy_pass http://${CREATE_STARTUP_URL};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /v1/api/startups/read {
        proxy_pass http://${READ_STARTUP_URL};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /v1/api/startups/update {
        proxy_pass http://${UPDATE_STARTUP_URL};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /v1/api/startups/delete {
        proxy_pass http://${DELETE_STARTUP_URL};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Rutas para Technologies
    location /v1/api/technologies/create {
        proxy_pass http://${CREATE_TECHNOLOGY_URL};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /v1/api/technologies/read {
        proxy_pass http://${READ_TECHNOLOGY_URL};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /v1/api/technologies/update {
        proxy_pass http://${UPDATE_TECHNOLOGY_URL};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /v1/api/technologies/delete {
        proxy_pass http://${DELETE_TECHNOLOGY_URL};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}