# Define un grupo de servidores para cada microservicio. 
# El nombre (ej. "create_startup") es una variable que usaremos más abajo.
# El "server" apunta al nombre del servicio en docker-compose y su puerto interno.

upstream create_startup {
    server ${CREATE_STARTUP_URL};
}
upstream read_startup {
    server ${READ_STARTUP_URL};
}
upstream update_startup {
    server ${UPDATE_STARTUP_URL};
}
upstream delete_startup {
    server ${DELETE_STARTUP_URL};
}

upstream create_technology {
    server ${CREATE_TECHNOLOGY_URL};
}
upstream read_technology {
    server ${READ_TECHNOLOGY_URL};
}
upstream update_technology {
    server ${UPDATE_TECHNOLOGY_URL};
}
upstream delete_technology {
    server ${DELETE_TECHNOLOGY_URL};
}


server {
    # El gateway escuchará en el puerto 80 (el puerto estándar de HTTP)
    listen 80;
    resolver 8.8.8.8;
    # Reglas de ruteo. Nginx buscará la primera que coincida.
    
    # Rutas para Startups
    location /v1/api/startups/create {
        proxy_pass http://create_startup; 
    }
    location /v1/api/startups/read {
        proxy_pass http://read_startup;
    }
    location /v1/api/startups/update {
        proxy_pass http://update_startup;
    }
    location /v1/api/startups/delete {
        proxy_pass http://delete_startup;
    }

    # Rutas para Technologies
    location /v1/api/technologies/create {
        proxy_pass http://create_technology;
    }
    location /v1/api/technologies/read {
        proxy_pass http://read_technology;
    }
    location /v1/api/technologies/update {
        proxy_pass http://update_technology;
    }
    location /v1/api/technologies/delete {
        proxy_pass http://delete_technology;
    }
}